import Head from 'next/head'
import React, { ReactElement, useEffect, useState } from 'react'
import { Status, State, Summary } from '../@types'
import styles from '../styles/Home.module.css'
import { getData, getSummary, getNetworks } from '../utils/getData'

export default function HomePage(): ReactElement {
  const [network, setNetwork] = useState<number>(3)
  const [networks, setNetworks] = useState<string[]>()
  const [statuses, setStatuses] = useState<Status[]>()
  const [summary, setSummary] = useState<Summary[]>()

  function style(state: State) {
    console.log('state', state)
    if (state === State.Down) {
      return styles.down
    } else if (state === State.Warning) {
      return styles.warning
    } else {
      return styles.up
    }
  }

  useEffect(() => {
    async function getStatuses() {
      const statusData = await getData()
      if (statusData) setStatuses(statusData)

      const summaryData = getSummary(network, statuses)
      console.log('summaryData', summaryData)
      if (summaryData) setSummary(summaryData)

      const networksData = getNetworks(statuses)
      console.log('networksData', networksData)
      if (networksData) setNetworks(networksData)
    }
    getStatuses()
  }, [network])

  console.log('summary', summary)
  console.log('~ networks', networks)

  return (
    <div className={styles.container}>
      <Head>
        <title>Ocean Protocol Status</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Ocean Status</h1>
        <p className={styles.description}>
          Current Status of Ocean Components{' '}
        </p>
        <div className={styles.grid}>
          {networks && (
            <>
              {networks.map((value: string) => (
                <div key={value} className={`${styles.network}`}>
                  {value}
                </div>
              ))}
            </>
          )}
        </div>
        <div className={styles.grid}>
          {summary && (
            <>
              {summary.map((value: Summary) => (
                <div
                  key={value.component}
                  className={`${styles.card} ${style(value.status)}`}
                >
                  <h2>{value?.component}</h2>
                  <p>{value?.status}</p>
                </div>
              ))}
            </>
          )}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
