import Head from 'next/head'
import React, { ReactElement, useEffect, useState } from 'react'
import { Status, State, Summary } from '../@types'
import styles from '../styles/Home.module.css'
import { getData, getSummary } from '../utils/getData'

export default function HomePage(): ReactElement {
  const [network, setNetwork] = useState<number>(0)
  const [data, setData] = useState<Summary[]>([
    {
      component: 'Loading',
      status: State.Up
    }
  ])

  function style(state: State) {
    console.log('state', state)
    if (state === State.Down) {
      return styles.down
    } else if (state === State.Warning) {
      return styles.warning
    } else {
      return styles.up
    }
  }

  useEffect(() => {
    async function getStatuses() {
      const summary = await getSummary(network)
      console.log('summary', summary)
      if (summary) setData(summary)
    }
    getStatuses()
  }, [network])

  console.log('data', data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Ocean Protocol Status</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Ocean Status</h1>
        <p className={styles.description}>
          Current Status of Ocean Components{' '}
        </p>
        <div className={styles.grid}>
          {data && (
            <>
              {data.map((value: Summary) => (
                <div className={`${styles.card} ${style(value.status)}`}>
                  <h2>{value?.component}</h2>
                  <p>{value?.status}</p>
                </div>
              ))}
            </>
          )}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

// <>
//   <div className={`${styles.card} ${style(data[0].status)}`}>
//     <h2>{data[0].component}</h2>
//     <p>{data[0].status}</p>
//   </div>
//   <div className={styles.card}>
//     <h2>Provider</h2>
//     <p>{statuses[network].provider.status}</p>
//   </div>

//   <div className={styles.card}>
//     <h2>Subgraph</h2>
//     <p>{statuses[network].subgraph.status}</p>
//   </div>

//   <div className={styles.card}>
//     <h2>Market</h2>
//     <p>{statuses[network].market}</p>
//   </div>
//   <div className={styles.card}>
//     <h2>Port</h2>
//     <p>{statuses[network].port}</p>
//   </div>
//   <div className={styles.card}>
//     <h2>Data Farming</h2>
//     <p>{statuses[network].dataFarming}</p>
//   </div>
//   <div className={styles.card}>
//     <h2>Operator Service</h2>
//     <p>{statuses[network].operator.status}</p>
//   </div>
//   {statuses[network].faucet.status && (
//     <div className={styles.card}>
//       <h2>Faucet</h2>
//       <p>{statuses[network].faucet.status}</p>
//     </div>
//   )}
//   <div className={styles.card}>
//     <h2>DAO Grants</h2>
//     <p>{statuses[network].daoGrants}</p>
//   </div>
// </>
// }
