import Head from 'next/head'
import React, { ReactElement, useEffect, useState } from 'react'
import { Status } from '../@types'
import styles from '../styles/Home.module.css'
import { getData } from '../utils/getData'

export default function HomePage(): ReactElement {
  const [statuses, setStatuses] = useState<Status[]>()
  const [network, setNetwork] = useState<number>(1)

  useEffect(() => {
    async function getStatuses() {
      const data = await getData()
      data && setStatuses(data)
      // console.log('statuses', statuses)
      // console.log('statuses?[1].aquarius.status', statuses[1].aquarius.status)
    }
    getStatuses()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Ocean Protocol Status</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Ocean Status</h1>
        <p className={styles.description}>
          Current Status of Ocean Components{' '}
        </p>
        <div className={styles.grid}>
          {statuses && (
            <>
              <div className={styles.card}>
                <h2>Aquarius</h2>
                <p>{statuses[network].aquarius.status}</p>
              </div>
              <div className={styles.card}>
                <h2>Provider</h2>
                <p>{statuses[network].provider.status}</p>
              </div>

              <div className={styles.card}>
                <h2>Subgraph</h2>
                <p>{statuses[network].subgraph.status}</p>
              </div>

              <div className={styles.card}>
                <h2>Market</h2>
                <p>{statuses[network].market}</p>
              </div>
              <div className={styles.card}>
                <h2>Port</h2>
                <p>{statuses[network].port}</p>
              </div>
              <div className={styles.card}>
                <h2>Data Farming</h2>
                <p>{statuses[network].dataFarming}</p>
              </div>
              <div className={styles.card}>
                <h2>Operator Service</h2>
                <p>{statuses[network].operator.status}</p>
              </div>
              {statuses[network].faucet.status && (
                <div className={styles.card}>
                  <h2>Faucet</h2>
                  <p>{statuses[network].faucet.status}</p>
                </div>
              )}
              <div className={styles.card}>
                <h2>DAO Grants</h2>
                <p>{statuses[network].daoGrants}</p>
              </div>
            </>
          )}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
